# Generated by Django 5.1.7 on 2025-03-12 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_newsitem_id_alter_tag_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='core.tag'),
        ),
    ]
