# Generated by Django 5.1.7 on 2025-03-12 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_newsitem_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='core.tag'),
        ),
    ]
