# Generated by Django 5.1.7 on 2025-03-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_newsitem_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='tag',
        ),
        migrations.AddField(
            model_name='newsitem',
            name='tag',
            field=models.ManyToManyField(related_name='news_items', to='core.tag'),
        ),
    ]
