# Generated by Django 5.1.7 on 2025-03-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_newsitem_tag_newsitem_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='dislikes',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsitem',
            name='likes',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
