# Generated by Django 5.1.7 on 2025-03-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_newsitem_dislikes_newsitem_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='dislikes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
    ]
