# Generated by Django 5.1.7 on 2025-03-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_coments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.RenameField(
            model_name='coments',
            old_name='content',
            new_name='comment',
        ),
    ]
